# Generated by Django 4.2.6 on 2023-11-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Prefer not to say', 'Prefer not to say'), ('Female', 'Female'), ('Male', 'Male')], max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'register_table',
            },
        ),
    ]
