# Generated by Django 5.0.2 on 2024-03-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='happy',
        ),
    ]
